version: '3.9'

services:
  nginx_prod:
    image: nginx:latest
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - ./nginx.server.conf:/etc/nginx/nginx.server.conf
      - ./graphql_server/:/etc/nginx/graphql_server
      - ./pnae/:/etc/nginx/pnae
      - ../certificates:/etc/nginx/certs
    ports:
      - "3003:443"
    networks:
      - pnae_prod_default
    restart: "on-failure"

networks:
  pnae_prod_default:
    external: true
