version: '3.9'

services:
  nginx_hmg:
    image: nginx:latest
    container_name: nginx_hmg
    volumes:
      - ./nginx.hmg.conf:/etc/nginx/nginx.conf
      - ./nginx.http.conf:/etc/nginx/nginx.http.conf
      - ./nginx.server.conf:/etc/nginx/nginx.server.conf
      - ./graphql_server/:/etc/nginx/graphql_server
      - ./pnae/:/etc/nginx/pnae
      - ./cmc/:/etc/nginx/cmc
      - ../certificates:/etc/nginx/certs
    ports:
      - "3002:443"
    networks:
      - pnae_hmg_default
      - cmc_hmg
    restart: "on-failure"

networks:
  pnae_hmg_default:
    external: true
  cmc_hmg:
    external: true
