services:
  nginx_dev:
    container_name: nginx_dev
    image: nginx:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx.http.conf:/etc/nginx/nginx.http.conf
      - ./nginx.server.conf:/etc/nginx/nginx.server.conf
      - ./graphql_server/:/etc/nginx/graphql_server
      - ./pnae/:/etc/nginx/pnae
      - ./cmc/:/etc/nginx/cmc
      - ../certificates:/etc/nginx/certs
      - ./pages/maintenance.html:/usr/share/nginx/html/maintenance.html
      - /home/apps/certificacao_cafe/src/presentation/web/.next/static:/usr/share/nginx/html/static
    ports:
      - "3001:443"
    networks:
      - cmc_dev
      - pnae_dev_default
    restart: "on-failure"

networks:
  cmc_dev:
    external: true
  pnae_dev_default:
    external: true
